# Generated by Django 3.2.6 on 2022-01-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_auto_20220105_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='kpp',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='ynp',
            field=models.IntegerField(blank=True),
        ),
    ]
